### ISSUE TITLE
Can't import tr and id locales

### ISSUE THREAD

**Issue by dsinkov-avanta** [date-fns/date-fns#1185]
version 2.0.0-alpha.27
I'm trying to import some locales, but can't import 2 of them
```javascript
import { pt, es, de, fr, id, tr, it } from 'date-fns/locale';
```
in browser console i see this
`"export 'id' was not found in 'date-fns/locale'`
`"export 'tr' was not found in 'date-fns/locale'`

and this locales doesn't work (i see `en` fallbacks), but other does.
for `tr` locale it's probably because it uses  
```javascript
var _index3 = require('../../../_lib/buildLocalizeArrayFn/index.js');
```
but there is no such file in my `node_modules` directory. And i have no idea what is wrong with `id` locale.

**Comment by kossnocorp** [comment]
Hey, thank you for your report. We've forgotten to remove these locales from the outdated locales list. I'll fix that and issue another release.

**Comment by kossnocorp** [comment]
The problem was fixed in `v2.0.0-alpha.30`: https://gist.github.com/kossnocorp/a307a464760b405bb78ef5020a4ab136#v200-alpha30

**Comment by dsinkov-avanta** [comment]
@kossnocorp thank you, but it still doesn't work properly. 
Probably your script in `scripts/build/indices.js` works not as expected. If i manually add imports to `esm/locale/index.js` 
```javascript
export { default as id } from './id/index.js'
export { default as tr } from './tr/index.js'
```
all works grate.

**Comment by kossnocorp** [comment]
Yeah, I forgot to rebuild the lib before release. Sorry about that. `v2.0.0-alpha.31` is on the way.

**Comment by kossnocorp** [comment]
`v2.0.0-alpha.31` is out: https://gist.github.com/kossnocorp/a307a464760b405bb78ef5020a4ab136#v200-alpha31

**Comment by dsinkov-avanta** [comment]
v2.0.0-alpha.31 works grate, thanks

**Comment by kossnocorp** [comment]
You're welcome!
