### ISSUE TITLE
Error when loading catalan locales

### ISSUE THREAD

**Issue by fxhrgco** [date-fns/date-fns#1248]
Hi there,

I'm having an `Module not found: Can't resolve 'date-fns/locale/ca'` when doing 
```
import ca from 'date-fns/locale/ca';
```
It seems that type + folder `ca` is there, how can I import it?

Thanks for your support,
Cheers

**Comment by kossnocorp** [comment]
Thank you for reporting it! We've forgotten to remove the locale from the outdated locales list, so that's why it's not present in the package. I'll fix that and issue a new version.

**Comment by fxhrgco** [comment]
Perfect! Thanks!

**Comment by kossnocorp** [comment]
It was fixed in v2.0.0-beta.3: https://gist.github.com/kossnocorp/a307a464760b405bb78ef5020a4ab136

**Comment by fxhrgco** [comment]
I've tried with the version v2.0.0-beta.3 but I am still not able to import it.
What's more I don't see the Catalan (CA) language support in the log but only the CY and KA.

**Comment by kossnocorp** [comment]
Something went wrong, damn :-( I'll check it.

**Comment by avizcaino** [comment]
@kossnocorp this should be closed as it is corrected in v2.0.0-beta.5, right?

**Comment by dkozickis** [comment]
@avizcaino that's right, thanks!
