### ISSUE TITLE
Fix exports in TS typings

### ISSUE THREAD

**Issue by kibertoad** [date-fns/date-fns#1290]
2.0.0-beta.4 with TypeScript 3.5.2 throws 12 TS errors when trying to use date-fns types during compilation:

```
../node_modules/date-fns/typings.d.ts:1131:3 - error TS2309: An export assignment cannot be used in a module with other exported elements.

1131   export = format
       ~~~~~~~~~~~~~~~

../node_modules/date-fns/typings.d.ts:1461:3 - error TS2309: An export assignment cannot be used in a module with other exported elements.

1461   export = max
       ~~~~~~~~~~~~

../node_modules/date-fns/typings.d.ts:1466:3 - error TS2309: An export assignment cannot be used in a module with other exported elements.

1466   export = min
       ~~~~~~~~~~~~

../node_modules/date-fns/typings.d.ts:1471:3 - error TS2309: An export assignment cannot be used in a module with other exported elements.

1471   export = parse
       ~~~~~~~~~~~~~~

../node_modules/date-fns/typings.d.ts:1901:3 - error TS2309: An export assignment cannot be used in a module with other exported elements.

1901   export = format
       ~~~~~~~~~~~~~~~

../node_modules/date-fns/typings.d.ts:2231:3 - error TS2309: An export assignment cannot be used in a module with other exported elements.

2231   export = max
       ~~~~~~~~~~~~

../node_modules/date-fns/typings.d.ts:2236:3 - error TS2309: An export assignment cannot be used in a module with other exported elements.

2236   export = min
       ~~~~~~~~~~~~

../node_modules/date-fns/typings.d.ts:2241:3 - error TS2309: An export assignment cannot be used in a module with other exported elements.

2241   export = parse
       ~~~~~~~~~~~~~~

../node_modules/date-fns/typings.d.ts:2671:3 - error TS2309: An export assignment cannot be used in a module with other exported elements.

2671   export = format
       ~~~~~~~~~~~~~~~

../node_modules/date-fns/typings.d.ts:3001:3 - error TS2309: An export assignment cannot be used in a module with other exported elements.

3001   export = max
       ~~~~~~~~~~~~

../node_modules/date-fns/typings.d.ts:3006:3 - error TS2309: An export assignment cannot be used in a module with other exported elements.

3006   export = min
       ~~~~~~~~~~~~

../node_modules/date-fns/typings.d.ts:3011:3 - error TS2309: An export assignment cannot be used in a module with other exported elements.

3011   export = parse
       ~~~~~~~~~~~~~~
```

**Comment by kibertoad** [comment]
@kossnocorp Any estimates on when next beta will be available? Would be nice to be able to check if this issue is fully resolved in our project now.

**Comment by kossnocorp** [comment]
I'm going to ship final v2 right now 🤫

**Comment by amunir9** [comment]
Still getting this issue in Angular 8.2.14 using  "typescript": "~3.7.2". 

One work around is adding 

 "compilerOptions": {
 
    "skipLibCheck": true,

}

in tsconfig.json

**Comment by kibertoad** [comment]
@amunir9 I've tried bumping TS used for linting and tests to 3.7.2, they are both still green: https://github.com/date-fns/date-fns/pull/1556

Could you try to reproduce the problem within `examples/typescript`?

**Comment by kibertoad** [comment]
@amunir9 Also, which version of date-fns are you using?

**Comment by daweedm** [comment]
+1

**Comment by kibertoad** [comment]
@daweedm can you reproduce it?

**Comment by daweedm** [comment]
No sorry, everything worked well before an update, I'm using the version 2.7.0

**Comment by Fetz** [comment]
I have the same issue with typescript:`3.7.5` the moment I added library that uses date-fns:`v2.11.1 but the current project is using  date-fns: `1.28.5`.

So I'm guessing that is typescript getting confused with 2 versions of data-fns...

**Comment by MikeMitterer** [comment]
date-fns is an absolute nightmare. This problem occurs, at least in my case, if I have different versions of date-fns in my node_modules.
